#!/usr/bin/env bash
python deps/rl-baselines3-zoo/train.py --algo ddpg --env PandaReach-v4 -n 50000 -optimize --n-trials 100 --n-jobs 16 --sampler random --pruner median --optimization-log-path logs/ppo_optimization.log
