#!/usr/bin/env bash
python deps/rl-baselines3-zoo/train.py --algo dqn --env PandaReachDenseDiscrete-v3 -n 5000 -optimize --n-trials 1000 --n-jobs 8 --sampler random --pruner median --optimization-log-path logs/dqn_optimization.log
