#!/usr/bin/env bash
python deps/rl-baselines3-zoo/train.py --algo ppo --env PandaPickAndPlace-v3 -n 5000 -optimize --n-trials 1000 --n-jobs 16 --sampler random --pruner median --optimization-log-path logs/ppo_optimization.log
