#!/usr/bin/env bash
python deps/rl-baselines3-zoo/train.py --algo dqn --env PandaPickAndPlaceDenseDiscrete-v3 -n 50000 -optimize --n-trials 1000 --n-jobs 4 --sampler random --pruner median --optimization-log-path logs/dqn_optimization.log
