#!/usr/bin/env bash

for env in PandaReach-v4 PandaReachDense-v4 PandaGrasp-v3 PandaGraspDense-v3 PandaPickAndPlace-v3 PandaPickAndPlaceDense-v3
do
    python deps/rl-baselines3-zoo/train.py --algo a2c --env $env -tb tb-logs -f logs/ --log-interval 5 --conf-file 'hyperparameters/a2c.yml'
done