PandaReach-v4:
  normalize: true
  n_envs: 20
  n_timesteps: !!float 5e5
  policy: 'MultiInputPolicy'
  ent_coef: 0.0
  max_grad_norm: 0.5
  n_steps: 50
  gae_lambda: 0.9
  vf_coef: 0.4
  gamma: 0.99
  use_rms_prop: True
  normalize_advantage: False
  learning_rate: lin_0.001
  use_sde: True
  policy_kwargs: "dict(log_std_init=-2, ortho_init=False)"

PandaReachDense-v4:
  normalize: true
  n_envs: 20
  n_timesteps: !!float 5e5
  policy: 'MultiInputPolicy'
  ent_coef: 0.0
  max_grad_norm: 0.5
  n_steps: 50
  gae_lambda: 0.9
  vf_coef: 0.4
  gamma: 0.99
  use_rms_prop: True
  normalize_advantage: False
  learning_rate: lin_0.001
  use_sde: True
  policy_kwargs: "dict(log_std_init=-2, ortho_init=False)"

PandaGrasp-v3:
  normalize: true
  n_envs: 20
  n_timesteps: !!float 2e6
  policy: 'MultiInputPolicy'
  ent_coef: 0.0
  max_grad_norm: 0.5
  n_steps: 50
  gae_lambda: 0.9
  vf_coef: 0.4
  gamma: 0.99
  use_rms_prop: True
  normalize_advantage: False
  learning_rate: lin_0.001
  use_sde: True
  policy_kwargs: "dict(log_std_init=-2, ortho_init=False)"

PandaGraspDense-v3:
  normalize: true
  n_envs: 20
  n_timesteps: !!float 2e6
  policy: 'MultiInputPolicy'
  ent_coef: 0.0
  max_grad_norm: 0.5
  n_steps: 50
  gae_lambda: 0.9
  vf_coef: 0.4
  gamma: 0.99
  use_rms_prop: True
  normalize_advantage: False
  learning_rate: lin_0.001
  use_sde: True
  policy_kwargs: "dict(log_std_init=-2, ortho_init=False)"

PandaPickAndPlace-v3:
  normalize: true
  n_envs: 20
  n_timesteps: !!float 2e6
  policy: 'MultiInputPolicy'
  ent_coef: 0.0
  max_grad_norm: 0.5
  n_steps: 50
  gae_lambda: 0.9
  vf_coef: 0.4
  gamma: 0.99
  use_rms_prop: True
  normalize_advantage: False
  learning_rate: lin_0.001
  use_sde: True
  policy_kwargs: "dict(log_std_init=-2, ortho_init=False)"

PandaPickAndPlaceDense-v3:
  normalize: true
  n_envs: 20
  n_timesteps: !!float 2e6
  policy: 'MultiInputPolicy'
  ent_coef: 0.0
  max_grad_norm: 0.5
  n_steps: 50
  gae_lambda: 0.9
  vf_coef: 0.4
  gamma: 0.99
  use_rms_prop: True
  normalize_advantage: False
  learning_rate: lin_0.001
  use_sde: True
  policy_kwargs: "dict(log_std_init=-2, ortho_init=False)"
